name: RankCommand
author: Phineas
version: 1.4
main: pw.phineas.rankcommand.Main
depend: [PermissionsEx]
commands:
  rankset:
    description: Rank set command
  rankreload:
    description: Reloads the plugin config
